### ISSUE TITLE
Error starting OpenSearch using Colima on Mac m1

### ISSUE THREAD

**Issue by soumil-kanwal-zomato** [abiosoft/colima#1005]
### Description

I am getting this error.

This is my docker compose.
`
image: opensearchproject/opensearch:2.5.0
environment:
  - discovery.type=single-node
  - plugins.security.disabled=true
  - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
ulimits:
  memlock:
    soft: -1
    hard: -1
  nofile:
    soft: 65536
    hard: 65536
volumes:
  - ./data/opensearch-data1:/usr/share/opensearch/data
ports:
  - 9200:9200
  - 9600:9600 # required for Performance Analyzer
networks:
  - net
`

`Caused by: java.nio.file.AccessDeniedException: /usr/share/opensearch/data/nodes 2024-03-21T11:06:56.741450445Z at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?] 2024-03-21T11:06:56.741451610Z at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?] 2024-03-21T11:06:56.741452816Z at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?] 2024-03-21T11:06:56.741453980Z at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[?:?] 2024-03-21T11:06:56.741456392Z at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?] 2024-03-21T11:06:56.741473899Z at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?] 2024-03-21T11:06:56.741477018Z at java.nio.file.Files.createDirectories(Files.java:793) ~[?:?] 2024-03-21T11:06:56.741494401Z at org.opensearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:313) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741607722Z at org.opensearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:251) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741610051Z at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:311) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741611506Z at org.opensearch.node.Node.<init>(Node.java:456) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741612878Z at org.opensearch.node.Node.<init>(Node.java:356) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741614209Z at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741615540Z at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741616829Z at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741618118Z at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.5.0.jar:2.5.0] 2024-03-21T11:06:56.741619324Z ... 6 more 2024-03-21T11:06:56.741472319Z uncaught exception in thread [main] 2024-03-21T11:06:56.742264650Z OpenSearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/opensearch/data/nodes]; 2024-03-21T11:06:56.742275212Z Likely root cause: java.nio.file.AccessDeniedException: /usr/share/opensearch/data/nodes 2024-03-21T11:06:56.742277125Z at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) 2024-03-21T11:06:56.742278539Z at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) 2024-03-21T11:06:56.742279953Z at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) 2024-03-21T11:06:56.742284486Z at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) 2024-03-21T11:06:56.742286274Z at java.base/java.nio.file.Files.createDirectory(Files.java:700) 2024-03-21T11:06:56.742287480Z at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) 2024-03-21T11:06:56.742288728Z at java.base/java.nio.file.Files.createDirectories(Files.java:793) 2024-03-21T11:06:56.742289934Z at org.opensearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:313) 2024-03-21T11:06:56.742291140Z at org.opensearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:251) 2024-03-21T11:06:56.742292470Z at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:311) 2024-03-21T11:06:56.742293718Z at org.opensearch.node.Node.<init>(Node.java:456) 2024-03-21T11:06:56.742300496Z at org.opensearch.node.Node.<init>(Node.java:356) 2024-03-21T11:06:56.742301744Z at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) 2024-03-21T11:06:56.742302950Z at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) 2024-03-21T11:06:56.742304156Z at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) 2024-03-21T11:06:56.742305279Z at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) 2024-03-21T11:06:56.742306443Z at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) 2024-03-21T11:06:56.742307649Z at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) 2024-03-21T11:06:56.742308855Z at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) 2024-03-21T11:06:56.742310061Z at org.opensearch.cli.Command.main(Command.java:101) 2024-03-21T11:06:56.742311225Z at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) 2024-03-21T11:06:56.742312390Z at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) 2024-03-21T11:06:56.742313554Z For complete error details, refer to the log at /usr/share/opensearch/logs/docker-cluster.log`
`
Have tried accessing using user id 1000 using userns_mode, other than that couldn't find anything else on internet

**Comment by soumil-kanwal-zomato** [comment]
Also tried using user: 501:20,
