### ISSUE TITLE
Crash on MacOS Sequioa 15.0 beta (24A5320a) from 13-08-2024

### ISSUE THREAD

**Issue by peterforeman** [abiosoft/colima#1109]
### Description

Since today, after installing the latest Sequioa beta, colima crashes on start. Previous beta worked fine.

```
$ colima start
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x102fd4d28]

goroutine 1 [running]:
github.com/abiosoft/colima/cmd.prepareConfig(0x10329ee20)
	github.com/abiosoft/colima/cmd/start.go:455 +0xa88
github.com/abiosoft/colima/cmd.init.func18(0x10329ee20, {0x10331bb80?, 0x0?, 0x102fdc1c4?})
	github.com/abiosoft/colima/cmd/start.go:96 +0x70
github.com/spf13/cobra.(*Command).execute(0x10329ee20, {0x10331bb80, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.1/command.go:970 +0x7e8
github.com/spf13/cobra.(*Command).ExecuteC(0x1032a0240)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/abiosoft/colima/cmd/root.Execute()
	github.com/abiosoft/colima/cmd/root/root.go:68 +0x24
main.main()
	github.com/abiosoft/colima/cmd/colima/main.go:12 +0x1c
```

I was using vz, but reset config by using 'colima delete' and 'colima start'. The colima delete did work, but start still crashes.

Config:
```
cpu: 2
disk: 100
memory: 2
arch: aarch64
runtime: docker
hostname: colima
kubernetes:
  enabled: false
  version: v1.30.0+k3s1
  k3sArgs:
    - --disable=traefik
autoActivate: true
network:
  address: false
  dns: []
  dnsHosts: {}
forwardAgent: false
docker: {}
vmType: qemu
rosetta: false
mountType: sshfs
mountInotify: true
cpuType: ""
provision: []
sshConfig: true
sshPort: 0
mounts: []
env: {}
```

After deleting the colima.yaml configuration file, I tried colima start again:

```
$ colima start
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0001] creating and starting ...                     context=vm
INFO[0001] downloading disk image ...                    context=vm
> QEMU binary "/opt/homebrew/bin/qemu-system-aarch64" seems properly signed with the "com.apple.security.hypervisor" entitlement
> "Attempting to download the image" arch=aarch64 digest= location=/Users/xxx/Library/Caches/colima/caches/fc0bfb9256e1f61294f2c41fc95ff4feb6c0daafccfb3b435e2d972e39bc8432.raw
> Downloaded the image from "/Users/xxx/Library/Caches/colima/caches/fc0bfb9256e1f61294f2c41fc95ff4feb6c0daafccfb3b435e2d972e39bc8432.raw"
> [hostagent] hostagent socket created at /Users/xxx/.colima/_lima/colima/ha.sock
> [hostagent] Using system firmware ("/opt/homebrew/share/qemu/edk2-aarch64-code.fd")
> exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/Users/xxx/.colima/_lima/colima/ha.stderr.log")
FATA[0021] error starting vm: error at 'creating and starting': exit status 1

$ colima start
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x1028c0d28]

goroutine 1 [running]:
github.com/abiosoft/colima/cmd.prepareConfig(0x102b8ae20)
	github.com/abiosoft/colima/cmd/start.go:455 +0xa88
github.com/abiosoft/colima/cmd.init.func18(0x102b8ae20, {0x102c07b80?, 0x0?, 0x1028c81c4?})
	github.com/abiosoft/colima/cmd/start.go:96 +0x70
github.com/spf13/cobra.(*Command).execute(0x102b8ae20, {0x102c07b80, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.1/command.go:970 +0x7e8
github.com/spf13/cobra.(*Command).ExecuteC(0x102b8c240)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/abiosoft/colima/cmd/root.Execute()
	github.com/abiosoft/colima/cmd/root/root.go:68 +0x24
main.main()
	github.com/abiosoft/colima/cmd/colima/main.go:12 +0x1c
```

It seems to crash on the line with "MacOS13OrNewer" in start.go (line 455):
```
	if util.MacOS() {
		if !cmd.Flag("network-address").Changed {
			startCmdArgs.Network.Address = current.Network.Address
		}
		if util.MacOS13OrNewer() {    // <---- here
			if !cmd.Flag("vm-type").Changed {
				startCmdArgs.VMType = current.VMType
			}
		}
		if util.MacOS13OrNewerOnArm() {
			if !cmd.Flag("vz-rosetta").Changed {
				startCmdArgs.VZRosetta = current.VZRosetta
			}
		}
		if util.MacOS15OrNewer() {
			if !cmd.Flag("nested-virtualization").Changed {
				startCmdArgs.NestedVirtualization = current.NestedVirtualization
			}
		}
	}
```

### Version

```
$ uname -a
Darwin MacBook-Pro-xxx.local 24.0.0 Darwin Kernel Version 24.0.0: Wed Aug  7 03:09:20 PDT 2024; root:xnu-11215.1.9~22/RELEASE_ARM64_T6000 arm64
$ colima version && limactl --version && qemu-img --version
colima version 0.7.1
git commit: ce7b155dbeb7843ac0d9966a6ad19dc8e3b56bb8
limactl version 0.22.0
qemu-img version 9.0.2
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
$ colima status
FATA[0000] colima is not running
```

### Reproduction Steps

1. Update to latest beta of Sequioa
2. colima start
3. crash

**Comment by peterforeman** [comment]
Macbook-Pro 16" 2021 (MacBookPro18,1 / Z14V000PRN/A)

**Comment by abiosoft** [comment]
I would push out a hotfix release once the PR finish building and gets merged.

**Comment by Tom1206** [comment]
Exactly the same issue here on my Macbook-Pro 16" 2021 on MacOS Sequoia Public Beta 4. I will try the hotfix when it will be released.

**Comment by abiosoft** [comment]
Can you kindly try the current development branch.

```sh
# remote stable version
brew uninstall colima

# install development version
brew install --head colima
```

**Comment by Tom1206** [comment]
For me this is working with the development version! Thank you!
```colima start
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0003] creating and starting ...                     context=vm
INFO[0015] provisioning ...                              context=docker
INFO[0015] starting ...                                  context=docker
INFO[0016] done

**Comment by abiosoft** [comment]
New release published https://github.com/abiosoft/colima/releases/tag/v0.7.3.

It may take a while for the new version to show up on homebrew.

If you prefer to move back to stable version later as things can occasionally break on the development versions. 

```
# remove current version
brew uninstall colima

# install stable version
brew install colima
```

**Comment by Tom1206** [comment]
Thank you very much!
