### ISSUE TITLE
Containers stop communicating with timeout failures between them

### ISSUE THREAD

**Issue by retromuz** [abiosoft/colima#351]
### Description

I'm on OSX Monterey 12.4. I have no trouble allocating memory. Having tried setting up limits in Colima instance one by one, but failing to get all containers communicate with each other. If I start them one by one, up to some point they communicate each other. However, at some point they stop. When they stop if I try to connect one of them and do something like, "ask for existing queues in localstack `docker exec -it awslocal bash -c "awslocal sqs list-queues"` ", it waits forever. At this stage, if I shutdown some of the other instances, the query gets processed.

I have allocated 45GB RAM (out of 64) to Colima. It barely goes over 25GB on my other ArchLinux machine.
I can see, before they all go to timeouts, the CPU usage drops to almost zero, even when some of them are still in the middle of starting up.

Before giving up, I fully unlocked limits by modifying `/etc/security/limits.conf`, `fs.file-max` and `fs.inotify.max_user_watches`

**Error seen on one of the services**
```10:39:50.860 [simpleMessageListenerContainer-2] WARN  o.s.c.a.m.l.SimpleMessageListenerContainer - An Exception occurred while polling queue 'dev-asset-processing-queue-v1'. The failing operation will be retried in 10000 milliseconds
com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2207)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2174)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2163)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1607)
	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1578)
	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$AsynchronousMessageListener.run(SimpleMessageListenerContainer.java:336)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	... 18 common frames omitted
```
`colima ssh`
`cat /etc/security/limits.conf`
```
* soft core unlimited
* hard core unlimited
* soft data unlimited
* hard data unlimited
* soft fsize unlimited
* hard fsize unlimited
* soft memlock unlimited
* hard memlock unlimited
* soft nofile 1048576
* hard nofile 1048576
* soft rss unlimited
* hard rss unlimited
* soft stack unlimited
* hard stack unlimited
* soft cpu unlimited
* hard cpu unlimited
* soft nproc unlimited
* hard nproc unlimited
* soft as unlimited
* hard as unlimited
* soft maxlogins unlimited
* hard maxlogins unlimited
* soft maxsyslogins unlimited
* hard maxsyslogins unlimited
* soft locks unlimited
* hard locks unlimited
* soft sigpending unlimited
* hard sigpending unlimited
* soft msgqueue unlimited
* hard msgqueue unlimite
```
`ulimit -aH`
```
core file size (blocks)         (-c) unlimited
data seg size (kb)              (-d) unlimited
scheduling priority             (-e) 0
file size (blocks)              (-f) unlimited
pending signals                 (-i) unlimited
max locked memory (kb)          (-l) unlimited
max memory size (kb)            (-m) unlimited
open files                      (-n) 1048576
POSIX message queues (bytes)    (-q) unlimited
real-time priority              (-r) 0
stack size (kb)                 (-s) unlimited
cpu time (seconds)              (-t) unlimited
max user processes              (-u) unlimited
virtual memory (kb)             (-v) unlimited
file locks                      (-x) unlimited
```
`ulimit -aS`
```
core file size (blocks)         (-c) unlimited
data seg size (kb)              (-d) unlimited
scheduling priority             (-e) 0
file size (blocks)              (-f) unlimited
pending signals                 (-i) unlimited
max locked memory (kb)          (-l) unlimited
max memory size (kb)            (-m) unlimited
open files                      (-n) 1048576
POSIX message queues (bytes)    (-q) unlimited
real-time priority              (-r) 0
stack size (kb)                 (-s) unlimited
cpu time (seconds)              (-t) unlimited
max user processes              (-u) unlimited
virtual memory (kb)             (-v) unlimited
file locks                      (-x) unlimited
```
`cat /proc/sys/fs/inotify/max_user_watches`
```
524288
```
`cat /proc/sys/fs/file-max`
```
4924292
```
`cat /proc/meminfo`
```
MemTotal:       49252360 kB
MemFree:        12107208 kB
MemAvailable:   35538952 kB
Buffers:          568176 kB
Cached:         27010268 kB
SwapCached:            0 kB
Active:          8934864 kB
Inactive:       25122020 kB
Active(anon):     127316 kB
Inactive(anon): 11269132 kB
Active(file):    8807548 kB
Inactive(file): 13852888 kB
Unevictable:     1508968 kB
Mlocked:         1508968 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               188 kB
Writeback:             0 kB
AnonPages:       7875952 kB
Mapped:          4753124 kB
Shmem:           5274108 kB
KReclaimable:    1283768 kB
Slab:            1388844 kB
SReclaimable:    1283768 kB
SUnreclaim:       105076 kB
KernelStack:       24256 kB
PageTables:        54060 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    24626180 kB
Committed_AS:   20927760 kB
VmallocTotal:   135290159040 kB
VmallocUsed:       32012 kB
VmallocChunk:          0 kB
Percpu:             5568 kB
AnonHugePages:   3319808 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
```
`sudo df -h`
```
Filesystem                Size      Used Available Use% Mounted on
devtmpfs                 10.0M         0     10.0M   0% /dev
shm                      23.5G         0     23.5G   0% /dev/shm
/dev/vda                240.2M    240.2M         0 100% /media/vda
tmpfs                    23.5G    475.4M     23.0G   2% /
tmpfs                     9.4G      1.1M      9.4G   0% /run
/dev/loop0               11.0M     11.0M         0 100% /.modloop
cgroup_root              10.0M         0     10.0M   0% /sys/fs/cgroup
/dev/disk/by-label/cidata
                          6.5M      6.5M         0 100% /mnt/lima-cidata
/dev/disk/by-label/data-volume
                         58.8G     20.9G     34.9G  37% /mnt/data
/dev/disk/by-label/data-volume
                         58.8G     20.9G     34.9G  37% /etc
/dev/disk/by-label/data-volume
                         58.8G     20.9G     34.9G  37% /home
/dev/disk/by-label/data-volume
                         58.8G     20.9G     34.9G  37% /root
/dev/disk/by-label/data-volume
                         58.8G     20.9G     34.9G  37% /tmp
/dev/disk/by-label/data-volume
                         58.8G     20.9G     34.9G  37% /usr/local
/dev/disk/by-label/data-volume
                         58.8G     20.9G     34.9G  37% /var/lib
:/Users/prageeth        929.1G    184.7G    744.4G  20% /Users/prageeth
:/tmp/colima            929.1G    184.7G    744.4G  20% /tmp/colima
/dev/disk/by-label/data-volume
                         58.8G     20.9G     34.9G  37% /var/lib/docker
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/21e5ae4f76a0edc41d922dbb8003e0de8bf58db51b4b0a253d4f2c213c35030b/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/d9f45709b22206bd9b09289c89d2f02ec8bfa0733d32f061af7f00c0d0f6a1e4/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/f4cda0f86ea556e43892ecd161f1f0285eb8b36249d84d13ee8f4ffb4f81c3a5/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/1379548948c600ea89713ead84d2ca933a34f23ca4477b7b8bf7bf0987d7f570/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/c62f04313f2395215369235fa9abccccbd49366aef0a12da89d45aa97a57852c/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/57769dbbd4a0f4e7767ab23de8ae11ac1b77ce0522a67d69c01b1d365ae28e71/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/c7046bf48b0b9ab0ee530e633cb898799cab7ae8b8424a1ae5540f4c0e310c92/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/4a72c79fa8d09e925de21778fc86bd8fef04174a03bec758aad090ac036a3e81/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/6c8bc90d8e3e0bbd9c606cbb3ac8f6d087d58f68c54511b56435e33353c37954/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/4c54216afb1371874ba41d3ee5cd4fe8a95a9fdcedef052f18c9d9dc69a859f6/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/1cd00ecb7ac8c170b5e0a0eec65cf0800a30bf0ce53cd8b8b438f0ff706d031e/merged
overlay                  58.8G     20.9G     34.9G  37% /var/lib/docker/overlay2/3dddb26cd748ab028d2f2beb3c4d04a41ec3886bcd0ec7088fdf8a48f192200a/merged
```
`docker stats`
```
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
e5cea1846689   awslocal         1.07%     270.6MiB / 46.97GiB   0.56%     48.1kB / 21.5kB   0B / 17.4MB      66
ee7cebd442db   mysql            0.12%     181MiB / 46.97GiB     0.38%     4.44MB / 6.49MB   34.7MB / 316MB   92
ae58bfe5e8fa   consul           0.69%     34.31MiB / 46.97GiB   0.07%     34.6kB / 59kB     0B / 0B          14
a4782a897191   elasticsearch    0.29%     1.381GiB / 46.97GiB   2.94%     21.5kB / 4.19kB   0B / 369kB       58
f1c83febf953   workflow         0.25%     652MiB / 46.97GiB     1.36%     81kB / 59.3kB     0B / 0B          66
22c6d7c03800   detection        0.67%     397MiB / 46.97GiB     0.83%     6.56kB / 2.21kB   0B / 0B          50
ee4b5a13289b   doc-conv         0.19%     1.309GiB / 46.97GiB   2.79%     7.69kB / 5.86kB   0B / 86kB        95
8f6d510a4df4   sentence-index   0.50%     357.8MiB / 46.97GiB   0.74%     10.8kB / 9.73kB   0B / 0B          92
9cf81e6ec98b   docs2            0.54%     383.7MiB / 46.97GiB   0.80%     19.7kB / 8.81kB   0B / 0B          83
c2d4a7ddf726   core2            0.54%     1.04GiB / 46.97GiB    2.21%     6.34MB / 4.3MB    0B / 0B          92
35842c4ba632   api2             0.48%     3.966GiB / 46.97GiB   8.44%     102kB / 108kB     0B / 0B          82
83ce4cf75194   app              105.04%   1014MiB / 46.97GiB    2.11%     1.51kB / 0B       0B / 4.1kB       29
```

### Version

Colima Version: 0.4.2
Lima Version: 0.11.1
Qemu Version: 7.0.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1.
2.
3.

### Expected behaviour

No timeout occurs while starting docker containers.

**Comment by retromuz** [comment]
I tried the same on Docker desktop (optimized for M1 chip). I'm seeing the same behavior.

**Comment by retromuz** [comment]
Today, I'm trying to reinstall AsahiLinux, after a full reinstall of MacOSX Moneterey (where Docker and Colima failed). AsahLinux installer itself is timing out.

Can this be a faulty hardware issue? This is a refurbished M1 Max MacBook Pro FYI.

<img width="666" alt="Screen Shot 2022-06-28 at 7 56 42 pm" src="https://user-images.githubusercontent.com/1218348/176151851-26e412c4-0e9d-4737-b928-c8132824c1d2.png">
