### ISSUE TITLE
VSCode Devcontainer unable to open inside container

### ISSUE THREAD

**Issue by MagicLegend** [abiosoft/colima#406]
### Description

Hi!

Seems like something is funky about how VSCode is trying to mount the current directory to the container. It throws the following:

```
[159 ms] Remote-Containers 0.245.2 in VS Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda).
[158 ms] Start: Resolving Remote
[170 ms] Setting up container for folder or workspace: /Users/<user>/Documents/private/colima-issue
[170 ms] Context: colima
[173 ms] Start: Check Docker is running
[173 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[203 ms] Server API version: 1.41
[203 ms] Start: Run: docker volume ls -q
[232 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/<user>/Documents/private/colima-issue --filter label=vsch.quality=stable
[250 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/<user>/Documents/private/colima-issue
[266 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/<user>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/<user>/Documents/private/colima-issue --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/<user>/Documents/private/colima-issue --log-level debug --log-format json --config /Users/<user>/Documents/private/colima-issue/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[371 ms] remote-containers 0.245.2.
[371 ms] Start: Run: docker buildx version
[551 ms] Start: Resolving Remote
[552 ms] Start: Run: git rev-parse --show-cdup
[560 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/<user>/Documents/private/colima-issue
[576 ms] local container features stored at: /Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/node_modules/vscode-dev-containers/container-features
[576 ms] Start: Run: tar --no-same-owner -x -f -
[588 ms] Start: Run: docker events --format {{json .}} --filter event=start
[589 ms] Start: Starting container
[590 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/<user>/Documents/private/colima-issue,target=/workspaces/colima-issue,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/Users/<user>/Documents/private/colima-issue --entrypoint /bin/sh danteev/texlive -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/<user>/Documents/private/colima-issue.
See 'docker run --help'.
[665 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/<user>/Documents/private/colima-issue
[682 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/<user>/Documents/private/colima-issue,target=/workspaces/colima-issue,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/Users/<user>/Documents/private/colima-issue --entrypoint /bin/sh danteev/texlive -c echo Container started
[682 ms] trap "exit 0" 15
[682 ms] exec "$@"
[682 ms] while sleep 1 & wait $!; do :; done -
[683 ms]     at MS (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2186)
[683 ms]     at Zw (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2124)
[683 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[683 ms]     at async KS (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:2006)
[683 ms]     at async co (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:3110)
[683 ms]     at async LP (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9352)
[683 ms]     at async DP (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9108)
[684 ms] Exit code 1
[685 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/<user>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/<user>/Documents/private/colima-issue --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/<user>/Documents/private/colima-issue --log-level debug --log-format json --config /Users/<user>/Documents/private/colima-issue/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[685 ms] Exit code 1
```

### Version

Colima Version: 0.4.4
Lima Version: 0.11.3
Qemu Version: 7.0.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

<Assuming [`Remote: Containers`](https://code.visualstudio.com/docs/remote/containers) is installed>

1. Create a `.devcontainer/devcontainer.json` file with the following content:
```
{
	"name": "TeX Live base",
	"image": "danteev/texlive",
	"extensions": ["james-yu.latex-workshop"]
}
```
2. Reopen in container (can be found by clicking on the green arrow in the bottom left)

### Expected behaviour

A working container.

**Comment by abiosoft** [comment]
Does switching to 9p mount resolve this?

```
colima start --mount-type 9p
```

**Comment by dacort** [comment]
Running into this same issue - anything I can do to help debug? On macOS Intel and latest colima.

**Comment by filiperochalopes** [comment]
I am having the same issue with my Mac Air M1

**Comment by DavidSchischke** [comment]
Is there an update to this? Running into the same issue

**Comment by michaelayoub** [comment]
In case anyone comes across this too: run `colima start --edit` and modify the mounts section like this. In my case my code directories are somewhere under my home directory; obviously, modify as necessary. The point is to have both the directory where your workspace is, or somewhere above it, and the `/tmp/devcontainers*` listed as writable in the mounts array:

```
mounts:
  - location: /Users/<me>/<top of path where my code is>
    writable: true
  - location: /tmp/devcontainers*
    writable: true
``` 

I'm using colima 0.8.1, docker 27.4.0, dev containers 0.401.0.

**Comment by 960208781** [comment]
https://marketplace.visualstudio.com/items?itemName=song-chaoyang.colima  vscode plugins
