### ISSUE TITLE
Error while fetching server API version

### ISSUE THREAD

**Issue by luisherrerameli** [abiosoft/colima#619]
### Description

Hey guys, how are you doing?
I am try to connect from python library https://docker-py.readthedocs.io/en/stable/ to docker daemon, but I am getting one issue:
`Traceback (most recent call last):
  File "/Users/luiherrera/Library/Caches/pypoetry/virtualenvs/fda2-core-tools-FxTA6xmY-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/luiherrera/Library/Caches/pypoetry/virtualenvs/fda2-core-tools-FxTA6xmY-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/luiherrera/Library/Caches/pypoetry/virtualenvs/fda2-core-tools-FxTA6xmY-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/luiherrera/AppsMeli/fda2-core-tools/fda2_core_tools/cli/clone_build_push_mpi.py", line 41, in main
    user_project = CloneBuildPusher(
  File "/Users/luiherrera/AppsMeli/fda2-core-tools/fda2_core_tools/utils/build_image.py", line 103, in __init__
    self._init_docker_client()
  File "/Users/luiherrera/AppsMeli/fda2-core-tools/fda2_core_tools/utils/build_image.py", line 139, in _init_docker_client
    self.docker_client = docker.from_env()
  File "/Users/luiherrera/Library/Caches/pypoetry/virtualenvs/fda2-core-tools-FxTA6xmY-py3.9/lib/python3.9/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/Users/luiherrera/Library/Caches/pypoetry/virtualenvs/fda2-core-tools-FxTA6xmY-py3.9/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/luiherrera/Library/Caches/pypoetry/virtualenvs/fda2-core-tools-FxTA6xmY-py3.9/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/luiherrera/Library/Caches/pypoetry/virtualenvs/fda2-core-tools-FxTA6xmY-py3.9/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))`

the library is try to connect the API with the url 'http+docker://localhost/version'

Some of you know how I could connect docler library with colima?

### Version

Colima Version:
Lima Version:
Qemu Version:

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Reproduction Steps

1. pip install docker
in python script
1. import docker
3. docker.from_env()

### Expected behaviour

docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

**Comment by abiosoft** [comment]
🤔 Does it work if you set `DOCKER_HOST` in the shell?

```
export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"
```

**Comment by luisherrerameli** [comment]
All is working fine now, thanks for your help.
